spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/basic_auth?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: victor
    password: senha123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
